export const COUNTRIES = [
    { name: "United States", code: "US", dial_code: "+1", max: 10, flag: "🇺🇸" },
    { name: "Afghanistan", code: "AF", dial_code: "+93", max: 9, flag: "🇦🇫" },
    { name: "Albania", code: "AL", dial_code: "+355", max: 9, flag: "🇦🇱" },
    { name: "Algeria", code: "DZ", dial_code: "+213", max: 9, flag: "🇩🇿" },
    { name: "Andorra", code: "AD", dial_code: "+376", max: 6, flag: "🇦🇩" },
    { name: "Anguilla", code: "AI", dial_code: "+1", max: 10, flag: "🇦🇮" },
    { name: "Argentina", code: "AR", dial_code: "+54", max: 10, flag: "🇦🇷" },
    { name: "Armenia", code: "AM", dial_code: "+374", max: 8, flag: "🇦🇲" },
    { name: "Australia", code: "AU", dial_code: "+61", max: 9, flag: "🇦🇺" },
    { name: "Austria", code: "AT", dial_code: "+43", max: 10, flag: "🇦🇹" },
    { name: "Azerbaijan", code: "AZ", dial_code: "+994", max: 9, flag: "🇦🇿" },
    { name: "Bahamas", code: "BS", dial_code: "+1", max: 10, flag: "🇧🇸" },
    { name: "Bahrain", code: "BH", dial_code: "+973", max: 8, flag: "🇧🇭" },
    { name: "Bangladesh", code: "BD", dial_code: "+880", max: 10, flag: "🇧🇩" },
    { name: "Barbados", code: "BB", dial_code: "+1", max: 10, flag: "🇧🇧" },
    { name: "Belarus", code: "BY", dial_code: "+375", max: 9, flag: "🇧🇾" },
    { name: "Belgium", code: "BE", dial_code: "+32", max: 9, flag: "🇧🇪" },
    { name: "Belize", code: "BZ", dial_code: "+501", max: 7, flag: "🇧🇿" },
    { name: "Benin", code: "BJ", dial_code: "+229", max: 8, flag: "🇧🇯" },
    { name: "Bermuda", code: "BM", dial_code: "+1", max: 10, flag: "🇧🇲" },
    { name: "Bhutan", code: "BT", dial_code: "+975", max: 8, flag: "🇧🇹" },
    { name: "Bolivia", code: "BO", dial_code: "+591", max: 8, flag: "🇧🇴" },
    { name: "Botswana", code: "BW", dial_code: "+267", max: 8, flag: "🇧🇼" },
    { name: "Brazil", code: "BR", dial_code: "+55", max: 11, flag: "🇧🇷" },
    { name: "Bulgaria", code: "BG", dial_code: "+359", max: 9, flag: "🇧🇬" },
    { name: "Cambodia", code: "KH", dial_code: "+855", max: 9, flag: "🇰🇭" },
    { name: "Cameroon", code: "CM", dial_code: "+237", max: 9, flag: "🇨🇲" },
    { name: "Canada", code: "CA", dial_code: "+1", max: 10, flag: "🇨🇦" },
    { name: "Chile", code: "CL", dial_code: "+56", max: 9, flag: "🇨🇱" },
    { name: "China", code: "CN", dial_code: "+86", max: 11, flag: "🇨🇳" },
    { name: "Colombia", code: "CO", dial_code: "+57", max: 10, flag: "🇨🇴" },
    { name: "Costa Rica", code: "CR", dial_code: "+506", max: 8, flag: "🇨🇷" },
    { name: "Croatia", code: "HR", dial_code: "+385", max: 9, flag: "🇭🇷" },
    { name: "Cuba", code: "CU", dial_code: "+53", max: 8, flag: "🇨🇺" },
    { name: "Cyprus", code: "CY", dial_code: "+357", max: 8, flag: "🇨🇾" },
    { name: "Czech Republic", code: "CZ", dial_code: "+420", max: 9, flag: "🇨🇿" },
    { name: "Denmark", code: "DK", dial_code: "+45", max: 8, flag: "🇩🇰" },
    { name: "Dominican Republic", code: "DO", dial_code: "+1", max: 10, flag: "🇩🇴" },
    { name: "Ecuador", code: "EC", dial_code: "+593", max: 9, flag: "🇪🇨" },
    { name: "Egypt", code: "EG", dial_code: "+20", max: 10, flag: "🇪🇬" },
    { name: "El Salvador", code: "SV", dial_code: "+503", max: 8, flag: "🇸🇻" },
    { name: "Estonia", code: "EE", dial_code: "+372", max: 8, flag: "🇪🇪" },
    { name: "Ethiopia", code: "ET", dial_code: "+251", max: 9, flag: "🇪🇹" },
    { name: "Fiji", code: "FJ", dial_code: "+679", max: 7, flag: "🇫🇯" },
    { name: "Finland", code: "FI", dial_code: "+358", max: 10, flag: "🇫🇮" },
    { name: "France", code: "FR", dial_code: "+33", max: 9, flag: "🇫🇷" },
    { name: "Georgia", code: "GE", dial_code: "+995", max: 9, flag: "🇬🇪" },
    { name: "Germany", code: "DE", dial_code: "+49", max: 11, flag: "🇩🇪" },
    { name: "Ghana", code: "GH", dial_code: "+233", max: 9, flag: "🇬🇭" },
    { name: "Greece", code: "GR", dial_code: "+30", max: 10, flag: "🇬🇷" },
    { name: "Guatemala", code: "GT", dial_code: "+502", max: 8, flag: "🇬🇹" },
    { name: "Haiti", code: "HT", dial_code: "+509", max: 8, flag: "🇭🇹" },
    { name: "Honduras", code: "HN", dial_code: "+504", max: 8, flag: "🇭🇳" },
    { name: "Hong Kong", code: "HK", dial_code: "+852", max: 8, flag: "🇭🇰" },
    { name: "Hungary", code: "HU", dial_code: "+36", max: 9, flag: "🇭🇺" },
    { name: "Iceland", code: "IS", dial_code: "+354", max: 7, flag: "🇮🇸" },
    { name: "India", code: "IN", dial_code: "+91", max: 10, flag: "🇮🇳" },
    { name: "Indonesia", code: "ID", dial_code: "+62", max: 11, flag: "🇮🇩" },
    { name: "Iran", code: "IR", dial_code: "+98", max: 10, flag: "🇮🇷" },
    { name: "Iraq", code: "IQ", dial_code: "+964", max: 10, flag: "🇮🇶" },
    { name: "Ireland", code: "IE", dial_code: "+353", max: 9, flag: "🇮🇪" },
    { name: "Israel", code: "IL", dial_code: "+972", max: 9, flag: "🇮🇱" },
    { name: "Italy", code: "IT", dial_code: "+39", max: 10, flag: "🇮🇹" },
    { name: "Jamaica", code: "JM", dial_code: "+1", max: 10, flag: "🇯🇲" },
    { name: "Japan", code: "JP", dial_code: "+81", max: 10, flag: "🇯🇵" },
    { name: "Jordan", code: "JO", dial_code: "+962", max: 9, flag: "🇯🇴" },
    { name: "Kazakhstan", code: "KZ", dial_code: "+7", max: 10, flag: "🇰🇿" },
    { name: "Kenya", code: "KE", dial_code: "+254", max: 9, flag: "🇰🇪" },
    { name: "Kuwait", code: "KW", dial_code: "+965", max: 8, flag: "🇰🇼" },
    { name: "Lebanon", code: "LB", dial_code: "+961", max: 8, flag: "🇱🇧" },
    { name: "Malaysia", code: "MY", dial_code: "+60", max: 10, flag: "🇲🇾" },
    { name: "Mexico", code: "MX", dial_code: "+52", max: 10, flag: "🇲🇽" },
    { name: "Morocco", code: "MA", dial_code: "+212", max: 9, flag: "🇲🇦" },
    { name: "Nepal", code: "NP", dial_code: "+977", max: 10, flag: "🇳🇵" },
    { name: "Netherlands", code: "NL", dial_code: "+31", max: 9, flag: "🇳🇱" },
    { name: "New Zealand", code: "NZ", dial_code: "+64", max: 9, flag: "🇳🇿" },
    { name: "Nigeria", code: "NG", dial_code: "+234", max: 10, flag: "🇳🇬" },
    { name: "Norway", code: "NO", dial_code: "+47", max: 8, flag: "🇳🇴" },
    { name: "Oman", code: "OM", dial_code: "+968", max: 8, flag: "🇴🇲" },
    { name: "Pakistan", code: "PK", dial_code: "+92", max: 10, flag: "🇵🇰" },
    { name: "Palestine", code: "PS", dial_code: "+970", max: 9, flag: "🇵🇸" },
    { name: "Panama", code: "PA", dial_code: "+507", max: 8, flag: "🇵🇦" },
    { name: "Peru", code: "PE", dial_code: "+51", max: 9, flag: "🇵🇪" },
    { name: "Philippines", code: "PH", dial_code: "+63", max: 10, flag: "🇵🇭" },
    { name: "Poland", code: "PL", dial_code: "+48", max: 9, flag: "🇵🇱" },
    { name: "Portugal", code: "PT", dial_code: "+351", max: 9, flag: "🇵🇹" },
    { name: "Qatar", code: "QA", dial_code: "+974", max: 8, flag: "🇶🇦" },
    { name: "Romania", code: "RO", dial_code: "+40", max: 9, flag: "🇷🇴" },
    { name: "Russia", code: "RU", dial_code: "+7", max: 10, flag: "🇷🇺" },
    { name: "Saudi Arabia", code: "SA", dial_code: "+966", max: 9, flag: "🇸🇦" },
    { name: "Singapore", code: "SG", dial_code: "+65", max: 8, flag: "🇸🇬" },
    { name: "South Africa", code: "ZA", dial_code: "+27", max: 9, flag: "🇿🇦" },
    { name: "South Korea", code: "KR", dial_code: "+82", max: 10, flag: "🇰🇷" },
    { name: "Spain", code: "ES", dial_code: "+34", max: 9, flag: "🇪🇸" },
    { name: "Sri Lanka", code: "LK", dial_code: "+94", max: 9, flag: "🇱🇰" },
    { name: "Sweden", code: "SE", dial_code: "+46", max: 9, flag: "🇸🇪" },
    { name: "Switzerland", code: "CH", dial_code: "+41", max: 9, flag: "🇨🇭" },
    { name: "Taiwan", code: "TW", dial_code: "+886", max: 9, flag: "🇹🇼" },
    { name: "Thailand", code: "TH", dial_code: "+66", max: 9, flag: "🇹🇭" },
    { name: "Turkey", code: "TR", dial_code: "+90", max: 10, flag: "🇹🇷" },
    { name: "Ukraine", code: "UA", dial_code: "+380", max: 9, flag: "🇺🇦" },
    { name: "United Arab Emirates", code: "AE", dial_code: "+971", max: 9, flag: "🇦🇪" },
    { name: "United Kingdom", code: "GB", dial_code: "+44", max: 10, flag: "🇬🇧" },
    { name: "Vietnam", code: "VN", dial_code: "+84", max: 9, flag: "🇻🇳" }
];
